### PR TITLE
MainMenu: Hide serial or UDP settings when necessary

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by jaxxzer** [comment]
What is the idea here?
When should serial/udp be visible and when should they not be?

**Comment by patrickelectric** [comment]
This PR turn udp visibility off when the connection is Serial and vice-versa.

**Comment by jaxxzer** [comment]
What if the user wants to switch the active connection?

If the user can change to a different serial configuration while connected to serial.. why must we not allow them to also change to a network connection?

The question might be, should we allow them to change the connection at all when a connection exists?

**Comment by patrickelectric** [comment]
>What if the user wants to switch the active connection?

Use the combobox to select the connection type.

> If the user can change to a different serial configuration while connected to serial.. why must we not allow them to also change to a network connection?

What ? They can change to udp or serial, and configure that is enabled.

> The question might be, should we allow them to change the connection at all when a connection exists?

Well, this is not what this PR is about, it just to remove unnecessary stuff when a connection configuration is enabled. And, besides that, I don't see why not.

**Comment by jaxxzer** [comment]
I was confused about what this was doing.

**Pull request merged**
