### PR TITLE
Move debug overlays to lower left corner

### PR DESCRIPTION
**Pull request by Williangalvani**
The debug window on top of the plot is really annoying. this moves it to the lower left corner:
Screenshot from 2019-08-02 14-50-14

Screenshot from 2019-08-02 14-54-16

### CODE REVIEW

**Comment by patrickelectric** [comment]
Right now the debug widget is over the replay menu button.
image

**Comment by jaxxzer** [comment]
> problem with replay button

what do you suggest? Is it really a problem?

**Comment by Williangalvani** [comment]
I think it would be nice to have it draggable around the screen, but I'm not sure of how to do that with qml

**Comment by patrickelectric** [comment]
> Is it really a problem? What do you suggest to resolve it?

Yes, since it is over the control button.

> I think it would be nice to have it draggable around the screen, but I'm not sure of how to do that with qml

Check `ValueReadout.qml`.

**Comment by jaxxzer** [comment]
> Yes, since it is over the control button.

I think that the patch is doing better than what we have today. Right now the item is over the main plot that you want to see. The collision of items in this patch is much less obstructive than we have in master, and this patch fixes #603 so why can't we merge it now? You can put another issue or push your own commits to improve it further. Right now we have a patch to improve master, ready to merge.

**Comment by jaxxzer** [comment]
> Right now we have a patch to improve master, ready to merge.

And we should generally merge things like that instead of waiting one week or more for something better to happen.

**Comment by patrickelectric** [comment]
Done in #651

**Pull request closed without merging**
