### PR TITLE
protocol update

### PR DESCRIPTION
**Pull request by jaxxzer**
Needs https://github.com/bluerobotics/ping-protocol-cpp/pull/56

### CODE REVIEW

**Comment by patrickelectric** [comment]
Can you rebase over ping-viewer master and get the new dev branch of ping-protocol-cpp ?

**Comment by patrickelectric** [comment]
you still need to rebase it over master.

**Comment by jaxxzer** [comment]
omg patrick give me a minute. I am off today to prepare for the trip.

**Comment by patrickelectric** [comment]
oh, sorry ! I thought that you only update the submodule and not rebased it over master.

**Comment by patrickelectric** [comment]
Thank you very much ! And sorry for any misunderstood.

**Pull request merged**
