### PR TITLE
Ping360Visualizer: Fix head down configuration

### PR DESCRIPTION
**Pull request by patrickelectric**
Ping360 head down configuration is not working in our current release, this fix the rotation logic with two rotation items 

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Review by Williangalvani — CHANGES_REQUESTED** [review]
CI is failing both due to style issues and something else (stalling?)

**Comment by patrickelectric** [comment]
> CI is failing both due to style issues and something else (stalling?)

mac is just stalling, that is normal from travis, where you saw the style problem ?

**Comment by Williangalvani** [comment]
> > CI is failing both due to style issues and something else (stalling?)
> 
> mac is just stalling, that is normal from travis, where you saw the style problem ?

My bad, I had both prs open, the issue was in the other one.

**Review by Williangalvani — APPROVED** [review]
LGTM, I'd just make sure that the heading integration also works well with the heads down configuration.

I'd merge as soon as we have user feedback that it works properly.

**Comment by patrickelectric** [comment]
@Williangalvani done, I tested here with by bench hardware but it would be nice to have a second check if everything is working as expected

**Review by Williangalvani — APPROVED** [review]

**Pull request merged**
