### PR TITLE
Ping360ControlPanel: Add advanced settings button

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix [#596](https://github.com/bluerobotics/ping-viewer/issues/596)

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by tcanabrava** [comment]
+1 for what willian said

**Comment by patrickelectric** [comment]
> The whole thing shifts down a little when the advanced options are toggled:

This is something related to PingItem check #617. This is fixed in the last version of this PR.

> I think the white line should be hidden too.

Removed to work like Ping1D.

> That empty space to the left of the icon is bothering me. I'm not sure of what to do to fix it. Maybe write "Advanced settings" in the empty space?

This is because we don't have some switches or other buttons to use the same, I'm aiming to use the same thing as we have already in Ping1D to maintain a consistent UI. I have added the firmware update button but with a disabled color to make you happier. 

Fixed.

**Comment by Williangalvani** [comment]
That is a lot better <3.
Can this be easily fixed?
```
default[Warning]: Ping360ControlPanel.qml(57) qrc:/Ping360ControlPanel.qml:57:13: QML RowLayout: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
```

Are these margins ok for hi-dpi displays too?

**Comment by patrickelectric** [comment]
> Can this be easily fixed?

Done.



> Are these margins ok for hi-dpi displays too?

Yes, they work as a normal margin, hidpi problem are usually something related to images or Qt configuration, this was fixed with 0a07b3458253eb8a58b3f2d2c6e2bc2266a6f349

But just to make sure:
normal screen:
image

macbook:
image

**Pull request merged**
