### PR TITLE
Fix linuxdeployqt

### PR DESCRIPTION
**Pull request by patrickelectric**
compile: Add libc6 copyright for linuxdeployqt

### CODE REVIEW

**Comment by jaxxzer** [comment]
Please add some comment about what/why and online reference if you have one.

**Comment by patrickelectric** [comment]
https://github.com/probonopd/linuxdeployqt/issues/340

**Comment by jaxxzer** [comment]
Wow long thread. For these kinds of problems when I had to go searching a long time for an answer, I like to add the link with reasoning + information directly inline with the text:

https://github.com/bluerobotics/battery-protector-firmware/blob/master/CMakeLists.txt#L11

Can you add some comment in the .sh.

**Comment by probonopd** [comment]
> Wow long thread.

Boils down to: What goes into an AppImage should be compiled on a system no newer than the oldest still-supported version of Ubuntu, which is currently Ubuntu xenial.

> Add libc6 copyright for linuxdeployqt

is just satisfying the test for now, but that is not going to work much longer as  tests may be added. linuxdeployqt `-unsupported-...` flags shall not be used and may break at any time.

**Pull request merged**
