### PR TITLE
opengl: set precision only for GL_ES

### LINKED ISSUE #888: t2.0.6 online displaying pink square
---
## Summary
Version: t2.0.6

Operating System: Windows 10 Pro, Intel® HD Graphics 3000, AMD Radeon HD 7400M Series
What is happening: PingViewer t2.0.6 displaying only pink square in Ping360

## Additional information
t2 0 6-error

### PR DESCRIPTION
**Pull request by jaxxzer**
inspired by https://github.com/pxscene/pxCore/pull/690

fix #888

### CODE REVIEW

**Comment by jaxxzer** [comment]
@espresso0000 can you please try this one and let me know about the pink square: https://ci.appveyor.com/api/buildjobs/sje4pvqlahi89ymt/artifacts/pingviewer_debug.zip

**Comment by espresso0000** [comment]
The procedure entry point ?qmlunregister@QQmlPrivate@@YAXW4RegistrationType@1@_K@Z count not be located in the dynamic link library pingviewer.exe

**Comment by jaxxzer** [comment]
@espresso0000 I see, sorry about that. I just tried here, and this one should work correctly. Can you please confirm it?
https://ci.appveyor.com/api/buildjobs/6d5mnqtc6oxr3ddg/artifacts/pingviewer_release.zip

**Comment by espresso0000** [comment]
@jaxxzer Yes it is working correctly.  (And tested with both Ping360 & Ping1D)

**Pull request merged**
