### PR TITLE
Ping360

### PR DESCRIPTION
**Pull request by patrickelectric**

### CODE REVIEW

**Comment by tcanabrava** [comment]
too hard to review 136 commits. this is one of the few cases where it's good to be squashed before commit. It's a new feature so there's not a problem for that.

**Comment by patrickelectric** [comment]
@tcanabrava I may squash some specific ones. This branch should be our actual "master", since I got a bit without time to organize things and create a "stable" branch for our 1.0 version, this one is our future 2.0 version of ping-viewer.

**Comment by patrickelectric** [comment]
Be free to send PRs based in device-manager to fix anything here :)

**Comment by patrickelectric** [comment]
pingviewer 1.x stable is in [**ping-viewer-1**](https://github.com/bluerobotics/ping-viewer/tree/ping-viewer-1) branch, we are merging device manager with our actual **master** branch to allow further development and avoid multiple development branch problems. 
This PR need to be accepted to allow the master branch merge. 

ping-viewer-1 should and will receive bug fixed and maybe a new stable release to fix any important problem for our users. Until there, core development should be done based in our new master branch (after this merge).

**Comment by jaxxzer** [comment]
> too hard to review 136 commits. this is one of the few cases where it's good to be squashed before commit. It's a new feature so there's not a problem for that.

@tcanabrava we misplaced our main development in this branch temporarily. All of these commits have already been reviewed as part of previous pull requests against this branch.

I agree with you, I just want to point out to you that this is not a normal pull request, and hopefully won't happen again.

**Pull request merged**
