### PR TITLE
Tools: Add testcomments

### PR DESCRIPTION
**Pull request by patrickelectric**
-Test PRs to have at least 10% of comments in .cpp files

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by jaxxzer** [comment]
oof. I feel like this could be a bad idea.

Why 10%? Why the .cpp in particular? 

The doxygen at least goes in the header. I would prefer a check that everything is doxygenated (we have this already?). 

The cpp we can take on a case-by-case basis and request more comments if necessary in the review. I don't think the algorithm for 'enough comments' can be so simple as x%.

**Comment by Williangalvani** [comment]
What happens if the PR is a simple fix and the patch has 2 lines and no comments?

**Comment by patrickelectric** [comment]
This is just something that I use in my internal projects, ok, closing PR.

**Comment by jaxxzer** [comment]
Do we have doxygen check?

**Comment by patrickelectric** [comment]
Yes, https://github.com/bluerobotics/ping-viewer/blob/master/tools/testdoxygen.sh.

**Pull request closed without merging**
