### PR TITLE
Move from wrench to arrow for configuration menu

### PR DESCRIPTION
**Pull request by patrickelectric**
Helps #667

### CODE REVIEW

**Comment by Williangalvani** [comment]
Could you make it only one color(blue) and make the background highlight on hover so we have more consistent buttons?
The slider buttons look good and are clearly buttons, the arrow not so much, and it looks out of place being black.
Peek 2019-09-23 11-37

**Comment by patrickelectric** [comment]
All our ping buttons have highlights when clicked, you can check in the menu. We don't have hover functionality to change the background as the native buttons, that's probably what you are missing. 
Also, this uses the same concept with the already existent buttons, it does not change it just moves from wrench to an arrow as the engineer team asked for.
We can add mouse area for all buttons in a different PR.

**Comment by patrickelectric** [comment]
@Williangalvani check: https://github.com/bluerobotics/ping-viewer/issues/767

**Comment by patrickelectric** [comment]
@Williangalvani My ping-viewer does not have this hover background feature.

**Comment by patrickelectric** [comment]
Peek 2019-09-23 12-13

**Comment by jaxxzer** [comment]
>  make it only one color(blue)

@Williangalvani video shows blue / black arrow between the two states. Check that before merege. The background thing should not block like @patrickelectric  pointed.

**Pull request merged**
